"""Add billing enrollment fields

Revision ID: 743f9468c8b1
Revises: c4a3b2d1e0f
Create Date: 2025-12-19 11:28:43.771402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '743f9468c8b1'
down_revision: Union[str, None] = 'c4a3b2d1e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_member')
    op.drop_table('config')
    op.drop_index('prompt_command', table_name='prompt')
    op.drop_table('prompt')
    op.drop_index('function_id', table_name='function')
    op.drop_table('function')
    op.drop_index('chatidtag_id', table_name='chatidtag')
    op.drop_table('chatidtag')
    op.drop_table('folder')
    op.drop_table('knowledge')
    op.drop_index('document_collection_name', table_name='document')
    op.drop_index('document_name', table_name='document')
    op.drop_table('document')
    op.drop_index('model_id', table_name='model')
    op.drop_table('model')
    op.drop_table('note')
    op.drop_table('channel')
    op.drop_index('memory_id', table_name='memory')
    op.drop_table('memory')
    op.drop_table('feedback')
    op.drop_table('message')
    op.drop_table('migratehistory')
    op.drop_index('tool_id', table_name='tool')
    op.drop_table('tool')
    op.drop_table('message_reaction')
    op.add_column('auth', sa.Column('email_hmac', sa.String(length=255), nullable=True))
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('auth', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.drop_index('auth_id', table_name='auth')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'share_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat', 'archived',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_index('chat_id', table_name='chat')
    op.drop_index('chat_share_id', table_name='chat')
    op.create_unique_constraint(None, 'chat', ['share_id'])
    op.alter_column('file', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index('file_id', table_name='file')
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('user', sa.Column('email_hmac', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('billing_customer_id', sa.String(length=255), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index('user_api_key', table_name='user')
    op.drop_index('user_id', table_name='user')
    op.drop_index('user_oauth_sub', table_name='user')
    op.create_index(op.f('ix_user_billing_customer_id'), 'user', ['billing_customer_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_email_hmac'), 'user', ['email_hmac'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_unique_constraint(None, 'user', ['oauth_sub'])
    op.create_unique_constraint(None, 'user', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email_hmac'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_billing_customer_id'), table_name='user')
    op.create_index('user_oauth_sub', 'user', ['oauth_sub'], unique=1)
    op.create_index('user_id', 'user', ['id'], unique=1)
    op.create_index('user_api_key', 'user', ['api_key'], unique=1)
    op.alter_column('user', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'billing_customer_id')
    op.drop_column('user', 'email_hmac')
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('file_id', 'file', ['id'], unique=1)
    op.alter_column('file', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_index('chat_share_id', 'chat', ['share_id'], unique=1)
    op.create_index('chat_id', 'chat', ['id'], unique=1)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('chat', 'archived',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat', 'share_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('auth_id', 'auth', ['id'], unique=1)
    op.alter_column('auth', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('auth', 'email_hmac')
    op.create_table('message_reaction',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('message_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('specs', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('valves', sa.TEXT(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True)
    )
    op.create_index('tool_id', 'tool', ['id'], unique=1)
    op.create_table('migratehistory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('migrated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('channel_id', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('parent_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('version', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('snapshot', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False)
    )
    op.create_index('memory_id', 'memory', ['id'], unique=1)
    op.create_table('channel',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('base_model_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('params', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False)
    )
    op.create_index('model_id', 'model', ['id'], unique=1)
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_name', 'document', ['name'], unique=1)
    op.create_index('document_collection_name', 'document', ['collection_name'], unique=1)
    op.create_table('knowledge',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('parent_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('items', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('is_expanded', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('chatidtag',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False)
    )
    op.create_index('chatidtag_id', 'chatidtag', ['id'], unique=1)
    op.create_table('function',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('valves', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('is_global', sa.INTEGER(), nullable=False)
    )
    op.create_index('function_id', 'function', ['id'], unique=1)
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('command', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('prompt_command', 'prompt', ['command'], unique=1)
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_member',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('channel_id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
